$(function(){
    $('.invite-click').on('click',function(){
        $('.mark-box').show();
        $('.share-box').show();
    });
    $('.share-box').on('click',function(){
        $('.mark-box').hide();
        $('.share-box').hide();
    })
})