<?php

return [
    '201802120' => [
        [
            'question' => '民间传统门神一般是郁垒和谁？',
            'answer' => '神茶',
            'dictionary' => '敬景保太土司卿郁卫尉迟门秦后茶神京都守',
            'batchSn' => '201802120',
            'answerLength' => 2,
        ],
        [
            'question' => '过年大人一般会给小孩发什么？',
            'answer' => '压岁钱',
            'dictionary' => '黄压平福红喜钱年乐月岁康拜神佑日保幸安',
            'batchSn' => '201802120',
            'answerLength' => 3,
        ],
        [
            'question' => '把福字倒过来贴有什么寓意？',
            'answer' => '福到了',
            'dictionary' => '平康到喜福乐压不去导幸倒心岁门齐开安了',
            'batchSn' => '201802120',
            'answerLength' => 3,
        ],
    ],
    '201802121' => [
        [
            'question' => '民间祭灶的日子是什么时候？',
            'answer' => '小年',
            'dictionary' => '神午五初福康至一端灶夕年小除王安财大十',
            'batchSn' => '201802121',
            'answerLength' => 2,
        ],
        [
            'question' => '年夜饭吃鱼表示什么？',
            'answer' => '年年有余',
            'dictionary' => '福喜乐齐年保安有欢岁幸鱼平余年月日佑康',
            'batchSn' => '201802121',
            'answerLength' => 4,
        ],
        [
            'question' => '“义取年胜年，籍以祈岁谂”是形容什么食物？',
            'answer' => '年糕',
            'dictionary' => '米佑粮糕康安月保食岁喜乐面年齐欢平福幸',
            'batchSn' => '201802121',
            'answerLength' => 2,
        ],
    ],
    '201802080' => [
        [
            'question' => '汤圆起源于哪个朝代？',
            'answer' => '宋朝',
            'dictionary' => '齐平胤宋唐宵欢乐安康赵保幸喜匡佑福朝元',
            'batchSn' => '201802080',
            'answerLength' => 2,
        ],
        [
            'question' => '唐朝被当做门神的两位武将是尉迟恭和谁？',
            'answer' => '秦叔宝',
            'dictionary' => '宝神武佑叔尉恭安幸欢迟喜齐平乐保康福秦',
            'batchSn' => '201802080',
            'answerLength' => 3,
        ],
        [
            'question' => '什么时候不能扫尘？',
            'answer' => '正月初一',
            'dictionary' => '齐正十腊安幸开月佑五康一心福八乐喜平初',
            'batchSn' => '201802080',
            'answerLength' => 4,
        ],
    ],
    '201802081' => [
        [
            'question' => '主持春晚次数最多的主持人是谁？',
            'answer' => '朱军',
            'dictionary' => '喜平阖巩乐军朱电赵央家冯安忠欢中台视李',
            'batchSn' => '201802081',
            'answerLength' => 2,
        ],
        [
            'question' => '由一根红绳编制而成的挂饰叫什么？',
            'answer' => '中国结',
            'dictionary' => '国佑美乐欢福红中黄保幸结华齐安绳喜康丽',
            'batchSn' => '201802081',
            'answerLength' => 3,
        ],
        [
            'question' => '春晚出现次数最多的节目是什么？',
            'answer' => '难忘今宵',
            'dictionary' => '乐幸宵平今忘难齐喜赵福红保安康欢山佑本',
            'batchSn' => '201802081',
            'answerLength' => 4,
        ],
    ],
    '201802090' => [
        [
            'question' => '除夕当天的晚饭一般叫什么？',
            'answer' => '年夜饭',
            'dictionary' => '康幸聚保夜上月佑齐欢喜岁年福平乐饭安晚',
            'batchSn' => '201802090',
            'answerLength' => 3,
        ],
        [
            'question' => '除夕的“夕”在传说中指什么？',
            'answer' => '年兽',
            'dictionary' => '保物平奥齐乐年幸福兽怪曼康佑安初喜欢特',
            'batchSn' => '201802090',
            'answerLength' => 2,
        ],
        [
            'question' => '春联普及于哪个朝代？',
            'answer' => '明朝',
            'dictionary' => '明平乐康宋雍福璋安幸朱齐喜元欢保正朝佑',
            'batchSn' => '201802090',
            'answerLength' => 2,
        ],
    ],
    '201802091' => [
        [
            'question' => '中央电视台每年除夕举办的节目叫什么？',
            'answer' => '春晚',
            'dictionary' => '春福乐保齐康安欢今幸山忘本佑晚宵喜难平',
            'batchSn' => '201802091',
            'answerLength' => 2,
        ],
        [
            'question' => '腌制腊味、口味偏甜，以哪个省最出名？   ',
            'answer' => '广东省',
            'dictionary' => '福幸省市北康安喜保东平广齐南京乐湖欢佑',
            'batchSn' => '201802091',
            'answerLength' => 3,
        ],
        [
            'question' => '“总把新桃换旧符”，这里桃符指？',
            'answer' => '春联',
            'dictionary' => '符保木头新平桃喜安联春子福康齐欢乐佑幸',
            'batchSn' => '201802091',
            'answerLength' => 2,
        ],
    ],
    '201802100' => [
        [
            'question' => '春联是哪位皇帝大力推广的？',
            'answer' => '朱元璋',
            'dictionary' => '元朱保乐康齐宋朝安欢平福隆佑明乾璋喜幸',
            'batchSn' => '201802100',
            'answerLength' => 3,
        ],
        [
            'question' => '唐朝被当做门神的两位武将是秦叔宝和谁？',
            'answer' => '尉迟恭',
            'dictionary' => '喜恭宝欢神佑叔安齐保武幸乐迟福康尉平秦',
            'batchSn' => '201802100',
            'answerLength' => 3,
        ],
        [
            'question' => '正月十五是什么节日？',
            'answer' => '元宵节',
            'dictionary' => '齐乐元平节喜晚年春欢佑保宵腊福康八幸安',
            'batchSn' => '201802100',
            'answerLength' => 3,
        ],
    ],
    '201802101' => [
        [
            'question' => '春节放爆竹盛行于哪个朝代？',
            'answer' => '宋朝',
            'dictionary' => '宋乐安胤朝唐幸保喜竹齐赵平佑欢匡康福爆',
            'batchSn' => '201802101',
            'answerLength' => 2,
        ],
        [
            'question' => '除夕是农历什么时候？',
            'answer' => '大年三十',
            'dictionary' => '欢年十喜保安五乐幸正三大八腊佑平福康齐',
            'batchSn' => '201802101',
            'answerLength' => 4,
        ],
        [
            'question' => '春节是农历什么时候？',
            'answer' => '正月初一',
            'dictionary' => '五福一欢喜腊安平乐佑幸保八康十齐月正初',
            'batchSn' => '201802101',
            'answerLength' => 4,
        ],
    ],
    '201802110' => [
        [
            'question' => '除夕守岁盛行于哪个朝代？',
            'answer' => '明朝',
            'dictionary' => '朱保佑幸正璋明元欢宋乐福朝平齐喜安康雍',
            'batchSn' => '201802110',
            'answerLength' => 2,
        ],
        [
            'question' => '春晚是每年什么时候举办？',
            'answer' => '除夕',
            'dictionary' => '康八齐喜平除乐安央保中欢春夕幸节腊佑福',
            'batchSn' => '201802110',
            'answerLength' => 2,
        ],
        [
            'question' => '上元节又叫什么节？',
            'answer' => '元宵节',
            'dictionary' => '平春欢节幸乐晚腊保喜宵八元福佑康年齐安',
            'batchSn' => '201802110',
            'answerLength' => 3,
        ],
    ],
    '201802111' => [
        [
            'question' => '元宵节南方一般吃什么？',
            'answer' => '汤圆',
            'dictionary' => '食康喜安米宵粥欢保汤平幸齐粮乐福面佑圆',
            'batchSn' => '201802111',
            'answerLength' => 2,
        ],
        [
            'question' => '元宵节是什么时候？',
            'answer' => '正月十五',
            'dictionary' => '正喜八平齐腊康佑一月保十五初安福乐欢幸',
            'batchSn' => '201802111',
            'answerLength' => 4,
        ],
        [
            'question' => '大年三十又叫什么？',
            'answer' => '除夕',
            'dictionary' => '央福夕佑安八中腊欢平春幸喜康除齐乐节保',
            'batchSn' => '201802111',
            'answerLength' => 2,
        ],
    ],
];